config/routes.rb
PwSplash::Application.routes.draw do
  resources :posts
  
  root :to => 'posts#new' #'splash#index'

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :sender_address, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new
    @post = Post.new
    respond_to { |format| format.html }
  end
  
  def create
    @post = Post.new(params[:post])
    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path }
        format.js 
      else
        STDERR.puts "Invalid email address. Not saving."
        format.html { render :action => "new"}
      end
    end
  end
  
  def show_all
    @post = Post.all
  end
  
  
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PwSplash</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag 'application' %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/create.js.erb
$('#post_email_field').val(function(){return '';});

$('#sent-alert').show();

app/views/posts/new.html.erb
<div class="spacer"></div>


<div id="center-box">

	<div id="logo-wrapper">
		Plugs & Wifi
	</div>
	
	<br>
	<p id="desc">
		    find work-friendly coffee shops,
		    libraries, hotel lobbies... anywhere you can just
		    walk in to get work done for an hour or an afternoon
	</p>
	
	<div class="spacer"></div>
	<p><strong>get on the list for our private beta:</strong></p>

	<%= form_for(@post, :remote => true, :url => {:action => 'create'}, :html => {:id => "form_id"} ) do |f| %>

	<% if @post.errors.any? %>
	   <div id="error_explanation">
	     <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

	     <ul>
	     <% @post.errors.full_messages.each do |msg| %>
	       <li><%= msg %></li>
	     <% end %>
	     </ul>
	   </div>
	 <% end %>

	 <div class="form-container">
	 	<div class="field">
		   <%= f.email_field :sender_address, {:id => "post_email_field", :placeholder => 'email@address.com'} %>
		 </div>
		
		<span id="sent-alert">Sent!</span>
		
		 <div class="actions">
		   <%= f.submit :value => 'Send' %>
		 </div>
	 </div>

	<% end %>

</div>

app/views/splash/index.html.erb
<h1>splash#index</h1>

<div id="notice"><%= notice%></div>

<p><%= link_to 'New Post', new_post_path %></p>